rails_app/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :faculties
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: 'home#index'

  get '/foo/bar', to: 'home#foo'
  put '/foo/:id/bar', to: 'home#put_bar'
  get '/foo/:id/bar', to: 'home#bar'
  put '/home/foo'
end

rails_app/app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    if user.has_role?('manager')
      can :manage, Faculty, :all
    else
      can :read, Faculty, :all
    end
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

rails_app/app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user
end

rails_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

rails_app/app/models/course.rb
class Course < ApplicationRecord
  has_and_belongs_to_many :students
end

rails_app/app/models/faculty.rb
class Faculty < ApplicationRecord
  validates :title, presence: true

  def notify_staff
    sleep 10
  end
end

rails_app/app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user
end

rails_app/app/models/student.rb
class Student < ApplicationRecord
  has_and_belongs_to_many :courses
end

rails_app/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  validates :email, presence: true, format: { with: /[^@]+@[^@]+/ }

  has_one :address
  has_many :notes, dependent: :destroy
  has_many :roles, class_name: 'User::Role'

  before_save :do_smth
  after_save :report_user_save

  def do_smth
    puts 'before save...'
  end

  def report_user_save
    puts "User was saved #{id} #{full_name}"
  end

  def has_role?(role)
    roles.any? { |r| role == r.role }
  end
end

rails_app/app/models/user/role.rb
class User::Role < ApplicationRecord
  belongs_to :user
end

rails_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale

  private

  def set_locale
    ::I18n.locale = params[:locale]
  end
end

rails_app/app/controllers/faculties_controller.rb
class FacultiesController < ApplicationController
  before_action :set_faculty, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index]

  # GET /faculties or /faculties.json
  def index
    @faculties = Faculty.all
  end

  # GET /faculties/1 or /faculties/1.json
  def show
  end

  # GET /faculties/new
  def new
    @faculty = Faculty.new
  end

  # GET /faculties/1/edit
  def edit
  end

  # POST /faculties or /faculties.json
  def create
    @faculty = Faculty.new(faculty_params)

    respond_to do |format|
      if @faculty.save
        format.html { redirect_to faculty_url(@faculty), notice: "Faculty was successfully created." }
        format.json { render :show, status: :created, location: @faculty }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @faculty.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /faculties/1 or /faculties/1.json
  def update
    authorize! :manage, @faculty
    respond_to do |format|
      if @faculty.update(faculty_params)
        NotifyStaffJob.perform_later(@faculty.id)
        format.html { redirect_to faculty_url(@faculty), notice: "Faculty was successfully updated." }
        format.json { render :show, status: :ok, location: @faculty }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @faculty.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /faculties/1 or /faculties/1.json
  def destroy
    @faculty.destroy

    respond_to do |format|
      format.html { redirect_to faculties_url, notice: "Faculty was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_faculty
    @faculty = Faculty.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def faculty_params
    params.require(:faculty).permit(:title)
  end
end

rails_app/app/controllers/home_controller.rb
class HomeController < ApplicationController
  protect_from_forgery except: [:put_bar]
  before_action :do_smth, only: [:index, :foo]

  def index
  end

  def foo
    @bar = params[:bar]
  end

  def bar
    render plain: "ID: #{params[:id]}, useful: #{params[:useful]}"
  end

  def put_bar
    render plain: "hello: #{params[:hello]}"
  end

  private

  def do_smth
    puts 'Doing something!!.....'
  end
end

rails_app/app/helpers/application_helper.rb
module ApplicationHelper
end

rails_app/app/helpers/faculties_helper.rb
module FacultiesHelper
end

rails_app/app/views/faculties/_faculty.html.erb
<div id="<%= dom_id faculty %>">
  <p>
    <strong>Title:</strong>
    <%= faculty.title %>
  </p>
</div>

rails_app/app/views/faculties/_form.html.erb
<%= form_with(model: faculty) do |form| %>
  <% if faculty.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(faculty.errors.count, "error") %> prohibited this faculty from being saved:</h2>

      <ul>
        <% faculty.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

rails_app/app/views/faculties/edit.html.erb
<h1>Editing faculty</h1>

<%= render "form", faculty: @faculty %>

<br>

<div>
  <%= link_to "Show this faculty", @faculty %> |
  <%= link_to "Back to faculties", faculties_path %>
</div>

rails_app/app/views/faculties/index.html.erb
<p style="color: green"><%= notice %></p>

<h1><%= t('faculties.index.title') %></h1>

<div id="faculties">
  <% @faculties.each do |faculty| %>
    <%= render faculty %>
    <p>
      <%= link_to "Show this faculty", faculty %>
    </p>
  <% end %>
</div>

<%= link_to t('faculties.add_new'), new_faculty_path, {class: 'btn btn-primary'} %>

rails_app/app/views/faculties/new.html.erb
<h1>New faculty</h1>

<%= turbo_frame_tag :user_form do %>
  <%= render "form", faculty: @faculty %>
<% end %>

<br>

<div>
  <%= link_to "Back to faculties", faculties_path %>
</div>

rails_app/app/views/faculties/show.html.erb
<%= turbo_frame_tag :user_form do %>
  <p style="color: green"><%= notice %></p>

  <%= render @faculty %>
<% end %>

<div>
  <% if can? :manage, @faculty %>
    <%= link_to "Edit this faculty", edit_faculty_path(@faculty), { class: 'btn btn-primary' } %>
    <%= link_to "Destroy this faculty", @faculty, { data: { turbo_method: :delete }, class: 'btn btn-danger' } %>
  <% end %>
  <p>
    <%= link_to "Back to faculties", faculties_path %>
  </p>
</div>

rails_app/app/views/home/foo.html.erb
<h2>Foo bar</h2>
<b>hello</b>, <%= 2 ** 6 %> <i>world</i>
<div>
  Bar: <%= @bar %>
</div>

rails_app/app/views/home/index.html.erb
<h1>Hello, world!</h1>
<div>
  <%= link_to "Faculties", faculties_url %>
</div>

rails_app/app/views/layouts/_login_status.html.erb
<% if current_user %>
  <div align="right">
    Logged in as <%= current_user.email %> |
    <%= link_to "Sign out", destroy_user_session_path,
                            data: { turbo_method: :delete }
    %>
  </div>
<% end %>

rails_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container-fluid">
      <%= render partial: '/layouts/login_status' %>
      <%= yield %>
    </div>
  </body>
</html>